### ISSUE TITLE
Onboarding Meeting Sep 13 , 2022

### ISSUE THREAD

**Issue by Yesh-2691** [smartcontractresearchforum/engagement#191]
- [x] PM process to be introduced while onbaording

**Comment by zubepaul** [comment]
### Notes
-Discussion about the format of these very notes. Discussion of creating just a singular thread for all of these meetings. The root issue will have a roll-up, reflect the up-to-date, and also resources. Otherwise alternate between agenda and notes for a thread. 
- Added to the agenda: Ticketing tool is going to change. Right now there are dashboard limitations so we'll move toward a better tool. #183 Will be worked out of here. 
- PM group update/proposal. What happens to new project proposals. 1 Pre-planning is when the proposal document needs to be collaborated on. Create new document from template gallery. Not all people will have access to the [proposal folder](https://drive.google.com/drive/u/0/folders/1Ob6whTUaVLkEx0cEg7qK6CVbyg2XjnEO). Add this to the onboarding process. **Action Item** Make sure to let people know how to do this and that it is valuable. Make sure to also show people the project tracking board **Action Item** @SirAh0 could add a link in our Discord potentially and know how to do interact with Documentation about this process will be stored Real needed steps for this should be address by the organization readme file efforts and thoughts #67 
- Goals and quests might work into #103 and #183 updates. 
- Needs for onboarding: what is the narrative/story of SCRF **Action Item**
- Onboarding goal reminders: Identify people who can provide value and how we can provide value to them as quickly as possible. Provide people with the tools they need to enjoy our community and contribute to our community. Know how to SCRF inline with our culture and process. 
- Discussion 
Help people to self identify and then give them a growth path that either does or does not immediately impact SCRF. Make sure to expose people to the all of the mechanics and elements of the organization and the story that helps them know why that happens here. Self-identification is likely going to be the first step, but how do we do that with some accuracy so that the experience does give them what they want. Automation can be a good replacement for upfront conversations so that the conversations that we do end up having are high impact quests
Quests:
- What's the story and create story board
- Know where all the information is stored
- What are the levels of process
- Quest vs. just read a file
- Make sure there are quest start processes that people can connect to from the forum. Need to make the whole of the organization linked together between .io, forum, chat. This should be one quest/onboarding process.
